-- +goose Up
-- The in-product AI agent (spec ai-agent): usage, tasks, agent runs and
-- run-now requests, detector samples, findings, proposals, assistant
-- sessions and messages, and the call quality columns of CDRs (S-5.1).
-- Ids of tasks, sessions, proposals and findings are uuids generated by
-- the application.

ALTER TABLE cdrs ADD COLUMN rtp_packets   BIGINT;
ALTER TABLE cdrs ADD COLUMN rtp_lost      BIGINT;
ALTER TABLE cdrs ADD COLUMN rtp_jitter_ms REAL;

CREATE TABLE ai_usage (
    day              DATE   PRIMARY KEY,
    input_tokens     BIGINT NOT NULL DEFAULT 0,
    output_tokens    BIGINT NOT NULL DEFAULT 0,
    reasoning_tokens BIGINT NOT NULL DEFAULT 0,
    calls            BIGINT NOT NULL DEFAULT 0
);

CREATE TABLE ai_sessions (
    id             UUID        PRIMARY KEY,
    owner          BIGINT      NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    title          TEXT        NOT NULL DEFAULT '',
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    last_active_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX ai_sessions_owner ON ai_sessions (owner, last_active_at DESC);

-- status: queued, running, succeeded, failed (S-15).
CREATE TABLE ai_tasks (
    id            UUID        PRIMARY KEY,
    kind          TEXT        NOT NULL,
    requested_by  BIGINT      NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    session_id    UUID        REFERENCES ai_sessions (id) ON DELETE CASCADE,
    replica       TEXT        NOT NULL,
    status        TEXT        NOT NULL DEFAULT 'queued'
                  CHECK (status IN ('queued', 'running', 'succeeded', 'failed')),
    error_code    TEXT,
    error_message TEXT,
    result        JSONB,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    started_at    TIMESTAMPTZ,
    finished_at   TIMESTAMPTZ
);
CREATE INDEX ai_tasks_status_replica ON ai_tasks (status, replica);
CREATE INDEX ai_tasks_created ON ai_tasks (created_at);

CREATE TABLE ai_agent_runs (
    id          BIGSERIAL   PRIMARY KEY,
    agent       TEXT        NOT NULL,
    replica     TEXT        NOT NULL,
    started_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    finished_at TIMESTAMPTZ,
    outcome     TEXT        CHECK (outcome IN ('ok', 'no_change', 'skipped_budget', 'skipped_locked', 'failed')),
    tokens      BIGINT      NOT NULL DEFAULT 0,
    detail      JSONB,
    error       TEXT
);
CREATE INDEX ai_agent_runs_agent ON ai_agent_runs (agent, started_at DESC);

CREATE TABLE ai_agent_requests (
    agent        TEXT        PRIMARY KEY,
    requested_by BIGINT      REFERENCES users (id) ON DELETE SET NULL,
    requested_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE ai_samples (
    kind    TEXT        NOT NULL,
    subject TEXT        NOT NULL,
    at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    value   JSONB       NOT NULL,
    PRIMARY KEY (kind, subject, at)
);
CREATE INDEX ai_samples_at ON ai_samples (at);

CREATE TABLE ai_findings (
    id               UUID        PRIMARY KEY,
    candidate_id     TEXT        NOT NULL,
    type             TEXT        NOT NULL,
    subject          TEXT        NOT NULL,
    severity         TEXT        NOT NULL CHECK (severity IN ('info', 'warning', 'critical')),
    status           TEXT        NOT NULL DEFAULT 'open'
                     CHECK (status IN ('open', 'acknowledged', 'dismissed', 'resolved')),
    title            TEXT        NOT NULL,
    evidence         JSONB       NOT NULL DEFAULT '{}',
    explanation      JSONB,
    explained        BOOLEAN     NOT NULL DEFAULT false,
    rank             INT,
    first_seen       TIMESTAMPTZ NOT NULL DEFAULT now(),
    last_seen        TIMESTAMPTZ NOT NULL DEFAULT now(),
    occurrences      BIGINT      NOT NULL DEFAULT 1,
    severity_history JSONB       NOT NULL DEFAULT '[]',
    acknowledged_by  BIGINT      REFERENCES users (id) ON DELETE SET NULL,
    acknowledged_at  TIMESTAMPTZ,
    dismissed_by     BIGINT      REFERENCES users (id) ON DELETE SET NULL,
    dismissed_at     TIMESTAMPTZ,
    dismiss_reason   TEXT,
    resolved_at      TIMESTAMPTZ
);
CREATE UNIQUE INDEX ai_findings_live_candidate ON ai_findings (candidate_id)
    WHERE status IN ('open', 'acknowledged');
CREATE INDEX ai_findings_candidate ON ai_findings (candidate_id, last_seen DESC);
CREATE INDEX ai_findings_status ON ai_findings (status, severity);

CREATE TABLE ai_proposals (
    id              UUID        PRIMARY KEY,
    source          TEXT        NOT NULL,
    session_id      UUID        REFERENCES ai_sessions (id) ON DELETE SET NULL,
    finding_id      UUID        REFERENCES ai_findings (id) ON DELETE SET NULL,
    fingerprint     TEXT        NOT NULL,
    title           TEXT        NOT NULL,
    rationale       TEXT        NOT NULL DEFAULT '',
    actions         JSONB       NOT NULL,
    config_revision BIGINT      NOT NULL,
    status          TEXT        NOT NULL DEFAULT 'open'
                    CHECK (status IN ('open', 'applied', 'failed', 'stale', 'dismissed', 'superseded')),
    created_by      BIGINT      REFERENCES users (id) ON DELETE SET NULL,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    applied_by      BIGINT      REFERENCES users (id) ON DELETE SET NULL,
    applied_at      TIMESTAMPTZ,
    dismissed_by    BIGINT      REFERENCES users (id) ON DELETE SET NULL,
    dismissed_at    TIMESTAMPTZ,
    dismiss_reason  TEXT,
    dismiss_text    TEXT,
    failure         JSONB
);
CREATE INDEX ai_proposals_fingerprint ON ai_proposals (fingerprint, status);
CREATE INDEX ai_proposals_status ON ai_proposals (status, created_at DESC);

CREATE TABLE ai_messages (
    id          BIGSERIAL   PRIMARY KEY,
    session_id  UUID        NOT NULL REFERENCES ai_sessions (id) ON DELETE CASCADE,
    role        TEXT        NOT NULL CHECK (role IN ('user', 'assistant')),
    content     TEXT        NOT NULL,
    tool_calls  JSONB,
    citations   JSONB,
    proposal_id UUID        REFERENCES ai_proposals (id) ON DELETE SET NULL,
    task_id     UUID        REFERENCES ai_tasks (id) ON DELETE SET NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX ai_messages_session ON ai_messages (session_id, id);

-- +goose Down
DROP TABLE ai_messages;
DROP TABLE ai_proposals;
DROP TABLE ai_findings;
DROP TABLE ai_samples;
DROP TABLE ai_agent_requests;
DROP TABLE ai_agent_runs;
DROP TABLE ai_tasks;
DROP TABLE ai_sessions;
DROP TABLE ai_usage;
ALTER TABLE cdrs DROP COLUMN rtp_jitter_ms;
ALTER TABLE cdrs DROP COLUMN rtp_lost;
ALTER TABLE cdrs DROP COLUMN rtp_packets;
