apiVersion: v1
data:
  nonceSecret: ENC[AES256_GCM,data:qd0Ej8JIoKtH4FWyeHiE89CswmpHtjM2OphiXYxkUJh7gXbKFnVuPN9SSaNRw7Y3j+VSBfbg5dFFupls9SlRqkaDntVbQEz+oTspfwXgUgcsDCICShoviw==,iv:pVEg6uPnoX5tikN4L7+WXQLiidrE2ONNfDFcFJ2BDYo=,tag:HwWJsGOQW6Aap9f2+WOgjQ==,type:str]
kind: Secret
metadata:
  name: hello-nonce
  namespace: hello
  annotations:
    sync.kuvryn.io/prune: disabled
  labels:
    app.kubernetes.io/managed-by: kuvryn-sync
type: Opaque
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHU05mUzluSkV2czI4bk1D
        Y0VaQjdhdVlyU3ZzN1doR3pXUnljL3daeEdNCmQ2WVNBaFFLYlUzbUVNdmM1NFFL
        NGtmSXQ1OWQyenRtd1hOcUJ1WkUyZmsKLS0tIGd3VzMwbmhudFZNTDFDNDJaRXlQ
        ZENnU05hVm0vQ2ROZkVFaCs0bm80eWcKWf6S5HHlF3IC0XD457IWp9qkcuRgzMhL
        Zu3GqqXV6hlKfWTeJYHeOR23C0e58nQUiugLkAvWHb8VKmEXxiEamg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age16r4tvtjglvsutkce9w2el3sfvu8jms0vxt8deke3vzxvecuxndks4e32wp
  encrypted_regex: ^(data|stringData|env)$
  lastmodified: "2026-10-04T09:11:34Z"
  mac: ENC[AES256_GCM,data:dGN0kIV+aNVaxdcJp6ix5vaXYXl1WLw9JH5b+MV5aUVUEsz1hipZ+jokPS/0nbE5/vLjxXy44P3dbDxtslrab7/MSj23uCWK5lKmmWdhivOnQPNPwA+6jzYs+TvYs7Uaf2trYo1zvltEkjfUJr1r47gZryMoQp77IsORe6Nqz4k=,iv:p7gLMDQ2MHWP0y1LHhUWCygMkEyFiXdkeIqwzm5HXRQ=,tag:eQ0IKjS+gtxup5QZDwf+rg==,type:str]
  version: 3.13.3
