apiVersion: v1
data:
  secretKey: ENC[AES256_GCM,data:cf9MSWl6drIjBDklLQeWFoW5GaRkpU/QjDYKh9T9i7O/ZqH7QWUtqbdQovRUgg6KrOWGbHix/4LshPQr,iv:J7kEp0nV6TMRjCbiLHZz3612tLNYx5fzwNzu7LnIV54=,tag:vqxOJwIQ+CRmAJcIAVHtcA==,type:str]
kind: Secret
metadata:
  name: hello-app
  namespace: hello
  annotations:
    sync.kuvryn.io/prune: disabled
  labels:
    app.kubernetes.io/managed-by: kuvryn-sync
type: Opaque
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4N1RDK25Pay91RTJXMkJu
        cytZN0JMSUxFcWEremJYZEJOMFk5d0R2VmdvClk3VzlxcFJseHJHREJrWllNQ0pk
        RmRxdWJBcmJWV1lBMDR1VVZiOWM5cUUKLS0tIGhwTXJlUm5DV2dkaWhYbklvK3J4
        MEJ5bDF2cDc1bnk2ZHJpMDJBeVgzbDgKrchSprNctQ0QpZnlcUiE3RSsYhHEZhZH
        Qks5JwBBomVawgJpJmQmyzIPlt3VpU/TajOgCwvhJ7jzO1pqOs/ayg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age16r4tvtjglvsutkce9w2el3sfvu8jms0vxt8deke3vzxvecuxndks4e32wp
  encrypted_regex: ^(data|stringData|env)$
  lastmodified: "2026-10-04T09:11:34Z"
  mac: ENC[AES256_GCM,data:wi7a+sz7k/lpCmYsdLbS6Fp6h3XqJpIUzAfB27vZZeA4n3Nno0Hgz2NXbkJS9M2fxZU0KXyxW7JDACd2OY+xKQI9z68loIlrKeUtasYL97yrNJCfEwU3EYj9MlTwojtTTw/iKeHJQmLeUWDYoIqwHG4I7Ait7IhBcCBxEVdRcks=,iv:qR5EnvgvvVi8g22//MkiNqQemnMK28T8nJClWyQDf14=,tag:yjHL5bYw4tsFMa0wuKpFcw==,type:str]
  version: 3.13.3
