apiVersion: v1
data:
  dsn: ENC[AES256_GCM,data:2t7MMuscXMQgSWQfQbTvEjVOrIKgVXoMDBpObuH8Tgw3TTif8zF/cG3Yau4YV3ZCm1lPH4pdmcNWQGSZS0kq9s4SMrUWZ7OvywJCFwv+Vkf25npaRXXhrBRNqOymzdpkjHpHxYXrjmeIlhWdcBCD72ZyZShyxLQKPeNGs6nxOFTgz1FxUe0B0w==,iv:QoEGhI1t65GMhFfZ2QvBcFfioqYOpjDtRQ1KSEgVrfg=,tag:ifyhRUNLecE2h5BYk8yCuw==,type:str]
  password: ENC[AES256_GCM,data:MV2BNHerM66hGoXEssPvyN59A7oQ6OjhZ8Rp2Fg7H0yBpLfqv8op3suxpJFGeJHliF5hpU8fWFLJwwgJm+TC/A==,iv:XiDVMVjoJFbMyPzvoqaHnB8pXuSA50LaXOtcAeLAl2s=,tag:VAR+d/+ZaXzqE1AbaRXSTA==,type:str]
  username: ENC[AES256_GCM,data:P85O8p2hwLk=,iv:QvtTi9BQH+YVKt1cxjWjTJmLqeLfDuOgWmi5Bf+IuAk=,tag:6ZgkVpSqssVpWHQzSYBS6Q==,type:str]
  minioRootPassword: ENC[AES256_GCM,data:y9ErUU/1lkbJPsR25oy1/i3NgXzwbMgDEkbxlCwMh1s=,iv:+0jAvXaQj4bMp3lkobQrr4c/rw518OBrCZ0DlKzInT4=,tag:043Iv3gybZ3K8g3sodNqAQ==,type:str]
  minioRootUser: ENC[AES256_GCM,data:xvWvPTULR0Lo4ns8nn0YnrUm5jjvVkOh,iv:iJHSRaUgP2XfKROgtphI45Z6kIBw7+ZXuxvEoDPvt+4=,tag:jwo1JkLeeQ8s8JWkNdtdNA==,type:str]
kind: Secret
metadata:
  name: hello-store
  namespace: hello
  annotations:
    sync.kuvryn.io/prune: disabled
  labels:
    app.kubernetes.io/managed-by: kuvryn-sync
type: Opaque
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHWk1NTkRyTmJQWVc5eWFv
        NXZjL0lrMi9YRTRHUXBQSGtPTis3L09hRVVnCjBob2UwRXVibDhxdmpsOUlxRlM3
        MFpGY0F4T29TUW4zdTZvSU9pS2Jpcm8KLS0tIGNzUEovS1dnM25Dc1pNa2tPb2p5
        Q3lWdjd3eVFyNE14NjdaOEhMeUQzdTQK6TIqIz+EPn8Wh6aFW5mL8ULUrUQJlT7D
        WhPaF59F6BWbMVru4PgToLY7mi4S145ngr/9O+ex8xiqVt89XEKvag==
        -----END AGE ENCRYPTED FILE-----
      recipient: age16r4tvtjglvsutkce9w2el3sfvu8jms0vxt8deke3vzxvecuxndks4e32wp
  encrypted_regex: ^(data|stringData|env)$
  lastmodified: "2026-10-04T17:02:36Z"
  mac: ENC[AES256_GCM,data:DbvG870rtp6ODHTSBxcmfSU7ITvk25k8Fw01pXOUT+0hpjcBJQ8SeJFquYog4IGWKMoO5ED3f/A99Oao3nJAUN902zSXkaYdds/M9L1mJgw5g0NBpkrPNVlOJrwUNOgF67vKrrS8uijePxZMABKaw2soRVBBEUcm4hYF1PLMq9g=,iv:p37k26+ZB3UkeNJCz2hkJKXSaCzEwiuyCPeP3CBsrqQ=,tag:J1gOqUZFqkA/Qa64J0dX2g==,type:str]
  version: 3.13.3
