apiVersion: v1
data:
    provider: ENC[AES256_GCM,data:oXGYcpmrlAE=,iv:/0gYFfJBXS+5rFAsypA900htYus4oKjurjM8AcwSggA=,tag:Z8sfcj2de4+qbFuhCF1kQQ==,type:str]
    base-url: ENC[AES256_GCM,data:2lbuazWadzfOHuD1YgRn5Ubyst3LJp15VL4UjtYJHYIa+rJ2AsZCUtEKoGjtWI5AkhsrjJoGVQu+/LJ44ycO00LI+18=,iv:wRaG5UVBYiXOA1WwgPbcPP5/SR5gxdWV3aOYvQPUiRw=,tag:ZIF8UzMK6smOlsZgsDov+Q==,type:str]
    model: ENC[AES256_GCM,data:UjsN4LGruAV8zD4u6CfMHOpTIeU=,iv:ov2au5rldP3XOiK6D+q9neGWoAERr5uery4+iF+iVZ4=,tag:TjuUIw3UMIk6FT/gOlqTKQ==,type:str]
    api-key: ENC[AES256_GCM,data:eE+4OGOqPWJPA03OfmhptN3p4lC/3TdZhTtreRTc7YDiqjgk60sA80HexKTyLNlKaqNs6vbMq2rvePEl05fzpwcMVCRB+Yq2nrmM0ROl/BK3lPNgfoYfCqscaM0=,iv:/ytTo+0twnwPvQ07RdBUqxr/6MZlGMVLH7Ik2bWQAjw=,tag:kKFZAXQfQ2gtjmioCDN/CA==,type:str]
kind: Secret
metadata:
    name: hello-ai
    namespace: hello
    annotations:
        sync.kuvryn.io/prune: disabled
    labels:
        app.kubernetes.io/managed-by: kuvryn-sync
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyRzZiVTV3MFo5S29DM0FF
            V2V2SjlHcjB2aytrd2FPRVJFVU94OGdHa1gwCmZkYU9pcnZTZVlxVVBOczJSb1kx
            VWZRVHZFZS9WYyt4cko5anJuUGdSZWsKLS0tIFlXT21pS0dWUlRWZ2VsbHZZY1Q2
            Y3dVRTFiY3pYUitxVVYzN01CWjZwMHcKqCJJAFajtC4fgfkXni5p3vQLdxEoQHk4
            mcK+G4MQ+Zwiu4UtF08DxkqdhHHhZSPQj7WHM2VjLqFxgrxjyxpd+g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16r4tvtjglvsutkce9w2el3sfvu8jms0vxt8deke3vzxvecuxndks4e32wp
    encrypted_regex: ^(data|stringData|env)$
    lastmodified: "2026-10-08T13:17:30Z"
    mac: ENC[AES256_GCM,data:UkxabauatZ8/p/HDIHRZ+mSgBJsrnxixX6MmXef+Uh+/2G7/3olj+jTw5U/xCeWB0OFomtmG8i/v34jQ6NmDAw1PmtGjoxsKzbD0xLZ97E7Pl4lURXyMxyruuGmX0JIqiCB/1izy+IgfVNHssoGKS3bZpqg+cSzdDy85Bz8kJLA=,iv:UIxAZpzk90MnwCzCnE8Lk6jlfLWvnFJdx0dzA0kOXrg=,tag:r0Ocq0ioea8sB8GLA2Cb5Q==,type:str]
    version: 3.13.3
